server:
  port: 8888

spring:
  application:
    name: config-service
  rabbitmq:
    stream:
      host: 127.0.0.1
      port: 5672
      username: guest
      password: guest
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file://${user.home}/Desktop/native-file-repo
        git:
#          uri: file:///Users/bong/Desktop/git-local-repo
          uri: https://github.com/bong01/msa-ecommerce
          search-paths: spring-cloud-config

management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh
